server:
  port: 1299
eureka:
  client:
    service-url:
      #将服务注册到eureka服务器
      defaultZone: http://localhost:7001/eureka
  instance:
    #服务实例名
    instance-id: pinggou-config-server-1299.com
    #显示ip地址
    prefer-ip-address: true
spring:
  application:
    #服务名
    name: PINGGOU-CONFIG-SERVER
  #配置使用本地的配置文件，如果使用github则不需要该配置
#  profiles:
#    active: native
  cloud:
    config:
      server:
        #配置本地配置文件的路径
#        native:
#          search-locations: E:/git-project/pinggou-springcloud-config
        #github路径
        git:
          uri: https://github.com/zb201666/pinggou-springcloud-config.git
          username: zb201666
          password: 196691zb
