server:
  port: 9527
spring:
  application:
    name: PINGGOU-ZUUL-GATEWAY
eureka:
  client:
    service-url:
      #将服务注册到的eureka服务器地址
      defaultZone: http://localhost:7001/eureka
  instance:
    #配置eureka服务器上显示的服务实例的别名
    instance-id: pinggou-zuul-gateway-9527.com
    prefer-ip-address: true
zuul:
  routes:
    plat:
      serviceId: pinggou-plat #这是调用满足条件的服务名，注意要小写
      path: /plat/** #这是所有路径前的通配
  ignored-services: "*" #用*来通配符，忽略从9527端口通过服务名来调用
  prefix: "/services" #这是所有路径的前缀
