server:
  port: 1299
eureka:
  client:
    service-url:
      #将服务注册到eureka服务器
      defaultZone: http://localhost:7001/eureka
  instance:
    #服务实例名
    instance-id: pinggou-config-server-1299.com
    #显示ip地址
    prefer-ip-address: true
spring:
  application:
    #服务名
    name: PINGGOU-CONFIG-SERVER
  cloud:
    config:
      server:
        #github路径
        git:
          uri: https://github.com/zb201666/pinggou-springcloud-config.git
          username: zb201666
          password: 196691zb
