server:
  port: 8001
spring:
  application:
    name: PINGGOU-PLAT
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    #为当前服务器添加实例的标识
    instance-id: pinggou-plat-8001.com
    prefer-ip-address: true